Update 23-hierarchical_data.Rmd
r4ds/bookclub-r4ds pull request #128
Opened 2024-04-01 00:51 UTC by andrewypua-projects

Request from Andrew Pua of r4ds Cohort 09  to add presented material to Chapter 23 Hierarchical Data.

2024-04-01 18:35 UTC, Ken-Vu requested changes
Hi, Andrew!  Can you move the sections **Cohort 8** and **Cohort 9** to the end of the presentation of Chapter 28?

2024-04-01 19:07 UTC, lgibson7 commented
@andrewypua-projects @Ken-Vu . I'll update it. Thank you!

2024-04-02 22:35 UTC, lgibson7 commented
@Ken-Vu I made some edits. Please review and approve if no major issues found.

2024-04-03 03:35 UTC, Ken-Vu approved these changes
Looks pretty good!  Thanks, Lydia!  Thanks, Andrew!

2024-04-03 03:35 UTC, merged