Update 24-web_scraping.Rmd
r4ds/bookclub-r4ds pull request #129
Opened 2024-04-01 00:54 UTC by andrewypua-projects

Request from Andrew Pua of r4ds Cohort 09 to add presented material to Chapter 24 Hierarchical Data.

2024-04-01 18:36 UTC, Ken-Vu requested changes
Hi, Andrew.  Can you move the sections labeled **Cohort 8** and **Cohort 9** to the end of the presentation?  Thanks!

2024-04-03 07:46 UTC, andrewypua-projects commented
I found the error for this part. I may have to put eval: FALSE in some places.

2024-04-07 04:43 UTC, Ken-Vu submitted a review, later dismissed

2024-04-07 04:55 UTC, Ken-Vu commented
@andrewypua-projects I moved the section **Meeting Videos** to the end of the presentation, which is something I recommend doing for consistency and keep the chapter less cluttered at the beginning.  I also removed the slide templates as well.  

Can you break up the section **Example: Loading IMDB data** into a series of smaller and shorter slides?  Otherwise, the slides render fine and look good!

2024-04-07 04:56 UTC, Ken-Vu approved these changes

2024-04-10 11:22 UTC, merged